enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[GooglePhotos]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

# [YouTube-Extended]
# build-mode = "apk"
# app-name = "YouTube"
# patches-source = "inotia00/revanced-patches"
# cli-source = "inotia00/revanced-cli"
# rv-brand = "ReVanced Extended"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

# [YouTube-anddea]
# build-mode = "apk"
# app-name = "YouTube"
# patches-source = "anddea/revanced-patches"
# integrations-source = "anddea/revanced-integrations"
# rv-brand = "anddea"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
# arch = "armeabi-v7a, arm64-v8a"

# [Reddit]
# build-mode = "apk"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# # archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Reddit-Extended]
build-mode = "apk"
version = "2024.17.0"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Facebook]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.facebook.orca"

[MyExpenses]
build-mode = "apk"
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[Photomath]
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
